version: '3'

services: 
  gateway:
    image: learn-azure-ms.azurecr.io/gateway
    environment: 
      GATEWAY_PORT: 80
      GATEWAY_NAME: gateway
      GATEWAY_SECONDARY_URL: http://gateway
    ports: 
      - '5000:80'
    
  secondary:
    image: learn-azure-ms.azurecr.io/secondary
    environment:
      SECONDARY_PORT: 80
      SECONDARY_NAME: secondary
    ports:
      - '5001:80'
